<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<div>
    <form action="<?php echo $this->getUrl('*/*/post/');?>" method="post" id="unsold-post-form" >
        <?php echo $this->getBlockHtml('formkey')?>
       <table width="50%" border="0" cellpadding="10" cellspacing="15" >
            <tr>
                <td class="a-left filter">
                    <div class="f-left">
                        <div><?php echo $this->__('From') ?>:&nbsp;<input class="input-text no-changes required-entry" type="text" id="period_date_from" name="report_from" value="<?php echo $this->getFilter('report_from') ?>" style="width:5em" /> <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" title="<?php echo $this->__('Select Date') ?>" id="period_date_from_trig" alt="<?php echo $this->__('Select Date') ?>" class="v-middle"/>&nbsp;&nbsp;</div>
                        <div id="period_date_from_advaice"></div>
                        </div>
                    <div class="f-left">
                        <div><?php echo $this->__('To') ?>:&nbsp;<input  class="input-text no-changes required-entry" type="text" id="period_date_to" name="report_to"  value="<?php echo $this->getFilter('report_to') ?>" style="width:5em" /> <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" class="v-middle" title="<?php echo $this->__('Select Date') ?>"id="period_date_to_trig" alt="<?php echo $this->__('Select Date') ?>"/>&nbsp;&nbsp;</div>
                        <div id="period_date_to_advaice"></div>
                    </div>
                    <div class="f-left">
                        <input class="scalable task" type="submit" name="do" value="Get Products"/>
                    </div>
                </td>
            </tr>
        </table>
    </form>
</div>
<script type="text/javascript">
    Calendar.setup({
        inputField : 'period_date_from',
        ifFormat : '%m/%e/%Y',
        button : 'period_date_from_trig',
        align : 'Bl',
        singleClick : true
    });
    Calendar.setup({
        inputField : 'period_date_to',
        ifFormat : '%m/%e/%Y',
        button : 'period_date_to_trig',
        align : 'Bl',
        singleClick : true
    });
</script>